### PR TITLE
Kill phantom

### PR DESCRIPTION
**Pull request by rbs392**
Killing phantomjs on worker exit

### CODE REVIEW

**Comment by rbs392** [comment]
Seems the phantomjs are not killed on exit of the worker. Need your comments

**Comment by tkazec** [comment]
Hi, is this an issue with Phantom 1 or just Phantom 2?

**Comment by rbs392** [comment]
Seems killing the worker by process.exit is not killing the phantom process I dont think it is a bug with phantom. Try setting workerShift to 1000 and chk pgrep phantom u can see the stale phantomjs 
(node v 5.10)

**Comment by jborden13** [comment]
@rbs392 thank you.  spent the whole day investigating memory leaks only to learn that my phantom processes were not being disposed of like they should've been.

**Comment by tkazec** [comment]
Thanks for the help! Published to `ghost-town@next`.

**Pull request closed without merging**
